language: node_js

node_js:
  - '0.10'

env:
  - TEST_SUITE=lint
  - TEST_SUITE=unit
  # - TEST_SUITE=integration

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script: "npm run test-${TEST_SUITE}"
